# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_urlparser_wrappers", use_symbols = TRUE, package_name = "urlparser")

#' @usage NULL
#' @useDynLib urlparser, .registration = TRUE
NULL

#' Parse a vector of URLs and return a DataFrame with parsed components
url_parse <- function(urls) .Call(wrap__url_parse, urls)


# nolint end
