# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_urlparser_wrappers", use_symbols = TRUE, package_name = "urlparser")

#' @usage NULL
#' @useDynLib urlparser, .registration = TRUE
NULL

#' Parse a vector of URLs and return a DataFrame with parsed components
parse_url <- function(urls) .Call(wrap__parse_url, urls)

parse_url_string <- function(urls) .Call(wrap__parse_url_string, urls)


# nolint end
